"""Generate the pipeline notebooks.

    python notebooks/_build_notebooks.py

Notebooks are generated from this script rather than hand-authored so that the
commands they contain stay in one editable place and the .ipynb JSON is never
edited by hand. Re-run it after changing the pipeline.

The notebooks document the ACTUAL pipeline as executed, including the attempts
that failed and why - a notebook that shows only the final happy path would omit
most of what was learned, and would let someone repeat the same mistakes.
"""

import json
from pathlib import Path

OUT_DIR = Path(__file__).resolve().parent


def md(*lines):
    return {"cell_type": "markdown", "metadata": {}, "source": _src(lines)}


def code(*lines):
    return {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": _src(lines),
    }


def _src(lines):
    text = "\n".join(lines)
    parts = text.split("\n")
    return [p + "\n" for p in parts[:-1]] + [parts[-1]]


def notebook(*cells):
    return {
        "cells": list(cells),
        "metadata": {
            "kernelspec": {
                "display_name": "legalai (.venv)",
                "language": "python",
                "name": "python3",
            },
            "language_info": {"name": "python", "version": "3.11"},
        },
        "nbformat": 4,
        "nbformat_minor": 5,
    }


def write(name, nb):
    path = OUT_DIR / name
    path.write_text(json.dumps(nb, indent=1), encoding="utf-8")
    print(f"wrote {path.name} ({len(nb['cells'])} cells)")


# ===========================================================================
# 01 - Environment, hardware feasibility, corpus
# ===========================================================================
nb1 = notebook(
    md(
        "# 01 - Environment, Hardware Feasibility, and Corpus",
        "",
        "Legal AI / PEFT pivot. Everything needed to get from a bare checkout to a",
        "machine that can serve three fine-tuned experts concurrently.",
        "",
        "**Target hardware:** RTX 4070 Laptop GPU, 8 GB VRAM, Windows 11.",
        "",
        "Run every cell from `legalai/`. All shell cells assume the venv interpreter",
        "at `.venv\\Scripts\\python.exe` - **not** bare `python`. That distinction",
        "cost several hours: on this machine bare `python` is the system interpreter,",
        "which has `torch` but not `peft`/`accelerate`/`bitsandbytes`, so the server",
        "started fine and then failed to load any model with a message saying to",
        "install a package that was already installed (in the venv).",
    ),
    md("## 1.1 Interpreter and dependencies"),
    code(
        "# The CUDA build of torch must come from PyTorch's own index. Installing",
        "# plain `torch` from PyPI on Windows silently gives a CPU-only build and",
        "# every model then runs on the CPU.",
        "!.venv\\Scripts\\python.exe -m pip install torch --index-url https://download.pytorch.org/whl/cu126",
        "!.venv\\Scripts\\python.exe -m pip install -r requirements-finetune.txt",
    ),
    code(
        "import torch",
        "print('torch', torch.__version__)",
        "print('cuda available', torch.cuda.is_available())",
        "print('device', torch.cuda.get_device_name(0) if torch.cuda.is_available() else 'n/a')",
        "print('bf16 supported', torch.cuda.is_bf16_supported() if torch.cuda.is_available() else 'n/a')",
        "",
        "# Verified working combination on the experiment machine:",
        "#   torch 2.13.0+cu126, transformers 5.14.1, peft 0.20.0, trl 1.9.2,",
        "#   bitsandbytes 0.50.0, accelerate 1.14.0, datasets 5.0.1",
    ),
    code(
        "# Confirm the interpreter you are about to use can see the whole stack.",
        "# run_experiment.ps1 performs this same check and refuses to start without it.",
        "import importlib.util as u",
        "missing = [m for m in ('torch','transformers','peft','accelerate','bitsandbytes','datasets')",
        "           if u.find_spec(m) is None]",
        "print('missing:', missing or 'none')",
    ),
    md(
        "## 1.2 Verify the models exist before designing around them",
        "",
        "Two of the three models named in the original pivot plan could not be used,",
        "and both were caught by querying the Hugging Face API rather than assuming:",
        "",
        "| planned | outcome |",
        "|---|---|",
        "| `meta-llama/Llama-3.2-3B-Instruct` | exists but `gated: manual` - needs an accepted licence + `HF_TOKEN`. Used Unsloth's ungated mirror of the same weights. |",
        "| `Qwen/Qwen2.5-3B-Instruct` | fine, ungated |",
        "| **Ministral 3B** | **has no open weights at all.** Mistral open-weighted only the 8B of Les Ministraux. The repo `ministral/Ministral-3b-instruct` was created 2024-03-14, seven months *before* Mistral announced Ministral, so it is an unrelated model reusing the name. |",
    ),
    code(
        "import json, urllib.request",
        "",
        "def hf_model(model_id):",
        "    try:",
        "        with urllib.request.urlopen('https://huggingface.co/api/models/' + model_id, timeout=25) as r:",
        "            d = json.load(r)",
        "        return dict(gated=d.get('gated'), downloads=d.get('downloads'),",
        "                    created=d.get('createdAt'), author=d.get('author'))",
        "    except Exception as exc:",
        "        return f'FAIL {exc}'",
        "",
        "for m in ['meta-llama/Llama-3.2-3B-Instruct',",
        "          'unsloth/Llama-3.2-3B-Instruct',",
        "          'Qwen/Qwen2.5-3B-Instruct',",
        "          'mistralai/Ministral-3b-instruct',   # 401 - does not exist",
        "          'ministral/Ministral-3b-instruct',   # third-party, predates the name",
        "          'microsoft/Phi-3.5-mini-instruct',",
        "          'ibm-granite/granite-3.1-2b-instruct']:",
        "    print(f'{m:45s}', hf_model(m))",
    ),
    md(
        "## 1.3 The hardware constraint that actually binds: grouped-query attention",
        "",
        "The first replacement for the third slot was Phi-3.5-mini. All three models",
        "**fitted in VRAM** with 252 MiB spare - so a weights-only check passes - but",
        "concurrent inference was impossible, because their combined KV cache needed",
        "roughly 2.1 GB.",
        "",
        "Phi-3.5-mini has **no grouped-query attention** (32 KV heads), costing",
        "384 KiB/token against Llama 3.2 3B's 112 and Qwen2.5 3B's 36.",
        "",
        "**Attention architecture, not parameter count, decides how many experts fit.**",
        "A residency check is not a sufficient feasibility test.",
    ),
    code(
        "# KV cache cost per token, computed from each model's own config.",
        "import json, urllib.request",
        "",
        "def kv_cost(model_id):",
        "    url = f'https://huggingface.co/{model_id}/raw/main/config.json'",
        "    with urllib.request.urlopen(url, timeout=25) as r:",
        "        c = json.load(r)",
        "    layers = c['num_hidden_layers']",
        "    heads = c['num_attention_heads']",
        "    kv_heads = c.get('num_key_value_heads', heads)",
        "    head_dim = c.get('head_dim') or c['hidden_size'] // heads",
        "    kib = layers * kv_heads * head_dim * 2 * 2 / 1024   # K and V, 2 bytes each",
        "    return dict(layers=layers, kv_heads=kv_heads, head_dim=head_dim,",
        "                gqa=kv_heads < heads, kib_per_token=round(kib))",
        "",
        "for m in ['unsloth/Llama-3.2-3B-Instruct', 'Qwen/Qwen2.5-3B-Instruct',",
        "          'microsoft/Phi-3.5-mini-instruct',      # 384 KiB/token - unusable here",
        "          'ibm-granite/granite-3.1-2b-instruct']:  # 80 KiB/token - chosen",
        "    print(f'{m:42s}', kv_cost(m))",
    ),
    md(
        "### Final expert assignment",
        "",
        "| role | base model | 4-bit VRAM | KV/token |",
        "|---|---|---|---|",
        "| legal | Llama 3.2 3B Instruct | 2206 MiB | 112 KiB |",
        "| news | Qwen2.5 3B Instruct | 1992 MiB | 36 KiB |",
        "| general_qa | Granite 3.1 2B Instruct | 1781 MiB | 80 KiB |",
        "| | **all three resident** | **5979 MiB** | 912 MiB @ 4096 tok |",
    ),
    md("## 1.4 Step 0 - concurrent residency check (run this before anything else)"),
    code(
        "# Loads all three models, generates from each, then runs three simultaneous",
        "# generations from three threads (what the PARALLEL topology does), and",
        "# budgets the KV cache. Writes finetune/vram_report.json.",
        "!set LEGALAI_USE_ADAPTERS=0 && .venv\\Scripts\\python.exe finetune\\check_vram.py --concurrent",
    ),
    md(
        "**Measured result: PASS** - 5979 MiB of weights, 1089 MiB free, 912 MiB of KV",
        "cache at the concurrent-phase context length.",
        "",
        "**Concurrency speedup: 1.07x**, against a theoretical ~3x. Three models sharing",
        "one GPU serialise at the compute level no matter how the graph dispatches them.",
        "This is reported in the paper: a concurrent topology chosen for latency reasons",
        "should be validated against the serving hardware first.",
    ),
    md(
        "## 1.5 Corpus",
        "",
        "Two problems, both silent:",
        "",
        "1. **The store held 44 stale news chunks, not the Act.** `AutoNewsFetcher` runs",
        "   with `clear_existing=True`, so any interactive query with news fetching on",
        "   replaces the statutory corpus. Every legal query would then abstain.",
        "2. **The Act's download URL is dead.** The Parliament PDF returns HTTP 202 with",
        "   an empty body and `eur-lex.europa.eu` answers non-browser clients with an",
        "   AWS WAF challenge (`x-amzn-waf-action: challenge`).",
        "",
        "Fix: ingest CELEX:32024R1689 - Regulation (EU) 2024/1689 as published in the",
        "Official Journal - via the EU Publications Office **Cellar** endpoint, which is",
        "built for machine access and requires an explicit `Accept-Language`.",
    ),
    code(
        "# Why the old sources fail, and the one that works.",
        "import requests",
        "for label, url, headers in [",
        "    ('parliament (dead)', 'https://www.europarl.europa.eu/doceo/document/TA-9-2024-0138_EN.pdf', {}),",
        "    ('eur-lex (WAF)',     'https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:32024R1689', {}),",
        "    ('cellar (works)',    'http://publications.europa.eu/resource/celex/32024R1689',",
        "                          {'Accept': 'application/pdf', 'Accept-Language': 'eng'}),",
        "]:",
        "    try:",
        "        r = requests.get(url, headers=headers, timeout=60)",
        "        print(f'{label:20s} {r.status_code} len={len(r.content):>9} pdf={r.content[:5] == b\"%PDF-\"}')",
        "    except Exception as exc:",
        "        print(f'{label:20s} FAIL {type(exc).__name__}')",
    ),
    code(
        "# Ingest. --replace clears first, which is required when the store holds",
        "# stale news chunks. embed.py RAISES rather than embedding an empty document",
        "# if every source fails - do not lower that length floor.",
        "!.venv\\Scripts\\python.exe embed.py --replace",
        "",
        "# Expect: 599,775 characters -> 644 chunks",
    ),
    code(
        "# Always verify before a run. A few hundred chunks is right; tens means the",
        "# corpus was overwritten by a news fetch.",
        "import utils",
        "print('chunks:', utils.get_db_document_count())",
    ),
    md(
        "## 1.6 Ollama is still required",
        "",
        "Generation is fully local via `transformers`, but **embeddings still run on",
        "Ollama**. If Ollama is down, `RetrievalAgent` logs `Dense vector search failed`",
        "and silently falls back to BM25-only - it completes, so a whole benchmark can",
        "run on half its retrieval stack with nothing in the output saying so.",
    ),
    code(
        "import config, requests",
        "from langchain_ollama import OllamaEmbeddings",
        "",
        "r = requests.get(config.OLLAMA_BASE_URL.rstrip('/') + '/api/tags', timeout=8)",
        "names = [m['name'] for m in r.json()['models']]",
        "print('embed model present:', any(config.OLLAMA_EMBEDDING_MODEL in n for n in names))",
        "",
        "vec = OllamaEmbeddings(model=config.OLLAMA_EMBEDDING_MODEL,",
        "                       base_url=config.OLLAMA_BASE_URL).embed_query('high-risk AI system')",
        "print('dense embedding dim:', len(vec))   # 768 for nomic-embed-text",
    ),
)

# ===========================================================================
# 02 - Dataset preparation
# ===========================================================================
nb2 = notebook(
    md(
        "# 02 - Dataset Preparation",
        "",
        "One supervised fine-tuning set per expert:",
        "",
        "| domain | source | why |",
        "|---|---|---|",
        "| legal | LegalBench (`nguha/legalbench`) | already cited in the paper's related work |",
        "| news | NewsQA (`lucadiliello/newsqa`) | preprocessed mirror of Trischler et al. 2017; the official `Maluuba/newsqa` needs a manual Microsoft download |",
        "| general | Dolly-15k (`databricks/databricks-dolly-15k`) | human-written, so no training on another model's outputs |",
        "",
        "**Two defects in the naive version of this, both of which produce adapters that",
        "look fine by loss and are useless in practice.**",
    ),
    md(
        "## 2.1 Defect 1 - benchmark targets are far too short",
        "",
        "LegalBench and NewsQA are *evaluation* benchmarks. Measured over our sample:",
        "",
        "- **105 of 112** loadable LegalBench tasks have mean answers of **10 characters",
        "  or fewer**; the median answer is **3 characters** (`Yes`, `No`, `UCC`).",
        "- Only **42 of 2375** sampled rows exceed 40 characters.",
        "- NewsQA answers are extractive spans averaging **26 characters**.",
        "",
        "The deployed agents are prompted for structured multi-sentence answers and",
        "scored against long references. Training directly on those targets teaches an",
        "expert to answer in three characters, which the judge scores as incomplete -",
        "an artefact that presents as *'specialisation made quality worse'*.",
    ),
    code(
        "# Reproduce the measurement.",
        "import json, collections, statistics",
        "rows = [json.loads(l) for l in open('finetune/data/legal_train.jsonl', encoding='utf-8')]",
        "by_task = collections.defaultdict(list)",
        "for r in rows:",
        "    by_task[r['source']].append(len(r.get('raw_answer', '')))",
        "means = sorted(((statistics.mean(v), k) for k, v in by_task.items()), reverse=True)",
        "print('tasks:', len(means))",
        "print('with mean raw answer <= 10 chars:', sum(1 for m, _ in means if m <= 10))",
        "for m, k in means[:5]:",
        "    print(f'  {m:7.1f} chars  {k}')",
    ),
    md(
        "**Fix:** render each target into the response format the agent is served",
        "behind, using only content already in the dataset - the task's question, the",
        "facts it supplies, and its ground-truth determination.",
        "",
        "Fields the datasets do not provide (notably **statutory citations**) are",
        "**omitted rather than filled**. Training a legal assistant to produce",
        "plausible-looking citations it cannot support is the worst available failure",
        "mode. No model generates any part of any training target.",
        "",
        "Result: mean target length **3.8 -> 420 chars** (legal), **26 -> 216** (news).",
    ),
    md(
        "## 2.2 Defect 2 - examples longer than the training window lose their target",
        "",
        "All three datasets put the target at the **end** of the rendered example, so an",
        "example longer than `--max-seq-length` is right-truncated into an input with",
        "**no answer attached**. A model trained on those produces a flat,",
        "plausible-looking loss curve rather than an error.",
        "",
        "At a 1400-char input cap and 512-token training window, **83% of NewsQA",
        "examples were over the limit** (NewsQA embeds a full article ahead of the",
        "question). The resulting news adapter did not learn: held-out loss ran",
        "**1.920 -> 1.923 -> 1.956** across three epochs with token accuracy static at",
        "0.568, while legal over the same budget improved 0.919 -> 0.844.",
        "",
        "The rate was also badly **uneven** - 83% news / 22% legal / 9% general - which",
        "is itself an inconsistency in effective training budget.",
    ),
    code(
        "# Dataset preparation. Defaults encode the fixes:",
        "#   MAX_INPUT_CHARS = 2800        (sized against a 1024-token training window)",
        "#   --legal-format irac          (structured targets, not bare labels)",
        "#   --news-format grounded       (answer span + the article sentence containing it)",
        "#   NewsQA articles are WINDOWED around the answer, not truncated from the start,",
        "#   because head-truncation often removes the very sentence the answer came from.",
        "!.venv\\Scripts\\python.exe finetune\\prepare_datasets.py --domain all",
    ),
    md(
        "`prepare_datasets.py` now **tokenises the rendered examples with each model's",
        "own tokenizer** and refuses to pass quietly above a 10% over-limit rate. That",
        "check is what makes this class of failure impossible to ship silently again.",
        "",
        "Final rates: **legal 0.0% / news 0.0% / general 0.7%**.",
    ),
    code(
        "# Inspect the manifest - this is the record to check BEFORE training.",
        "import json",
        "m = json.load(open('finetune/data/manifest.json', encoding='utf-8'))",
        "for domain, info in m['domains'].items():",
        "    tok = info['token_lengths']",
        "    print(f\"{domain:8s} n={info['train_examples']:5d} \"",
        "          f\"mean_target={info['mean_output_chars']:7.1f} chars  \"",
        "          f\"median={tok['median_tokens']:4d} tok  over_limit={tok['pct_over_limit']}%\")",
        "print()",
        "print('cross-domain overlap:', m['cross_domain_overlap'])",
        "print('target-length check :', m['target_length_check']['domains'])",
    ),
    code(
        "# Eyeball actual training examples. Do this - the numbers above cannot tell you",
        "# whether the target text is sensible.",
        "import json",
        "for domain in ('legal', 'news', 'general'):",
        "    r = json.loads(open(f'finetune/data/{domain}_train.jsonl', encoding='utf-8').readline())",
        "    print('=' * 70)",
        "    print(f\"{domain}  [{r['source']}]\")",
        "    print('INSTRUCTION:', r['instruction'][:160])",
        "    print('INPUT      :', r['input'][:200].replace(chr(10), ' | '))",
        "    print('TARGET     :', r['output'][:300].replace(chr(10), ' | '))",
    ),
    md(
        "## 2.3 Cross-domain leakage control",
        "",
        "The pivot plan asks that no query or source text be shared between the legal and",
        "news sets. Enforced two ways, both recorded in the manifest: exact dedupe by",
        "normalised hash, and token-Jaccard >= 0.6 against any legal record sharing a",
        "rare token (an inverted index keeps this from being an all-pairs comparison).",
        "",
        "On this sample the filter removed **nothing**, which is the expected outcome for",
        "contract-law tasks against CNN news articles. Reported rather than presented as",
        "a validated safeguard.",
    ),
)

# ===========================================================================
# 03 - QLoRA training
# ===========================================================================
nb3 = notebook(
    md(
        "# 03 - QLoRA Training",
        "",
        "Three adapters, one per expert. `train_qlora.py --role all` trains them",
        "sequentially, one model resident at a time.",
        "",
        "## The consistency requirement",
        "",
        "**Every adapter must be trained with the same budget.** If one expert gets more",
        "epochs, longer sequences or more examples than another, then a topology",
        "difference is partly *'which graph position holds the best-trained expert'* - a",
        "confound stacked on the model-position one the paper already discloses, and one",
        "entirely of our own making.",
        "",
        "So changing any hyperparameter means **retraining all three**, not topping up the",
        "ones not yet built. `train_qlora.py` enforces this: it resumes by default, but",
        "**aborts** if an existing adapter was trained on a different budget.",
    ),
    md(
        "## 3.1 Final hyperparameters, and the two revisions that got here",
        "",
        "| parameter | plan | final | why |",
        "|---|---|---|---|",
        "| epochs | 3 | **1** | held-out loss bottomed at epoch 1-2 on all three; epoch 3 made every adapter worse |",
        "| learning rate | 2e-4 | **5e-5** | answer length collapsed 161->68 words at 2e-4 |",
        "| max_seq_length | 1024 | **1024** | 512 truncated 83% of NewsQA targets (see nb 02) |",
        "| LoRA r / alpha / dropout | 16 / 32 / 0.05 | unchanged | |",
        "| effective batch | 8 | 8 | batch 1 x 8 grad-accum |",
        "| optimiser | paged AdamW 8-bit | unchanged | the QLoRA paper's choice |",
        "| quantisation | 4-bit NF4 + double quant | unchanged | |",
        "",
        "Cost: **~19-44 min per adapter, ~91 min for all three.**",
        "",
        "Targets are rendered through **each model's own chat template**, so an adapter is",
        "trained in the format it is served in. Training on a different scaffold than",
        "deployment is a common and avoidable reason a fine-tune appears not to have",
        "worked - and it bit us later at *validation* time (see nb 04).",
    ),
    code(
        "# Train all three. Defaults are the final values above, so no flags needed.",
        "!.venv\\Scripts\\python.exe -u finetune\\train_qlora.py --role all",
        "",
        "# Resumes by default: a completed adapter is skipped, so an interrupted run",
        "# continues instead of redoing ~50 minutes per expert. Use --force to overwrite.",
    ),
    md(
        "## 3.2 Evaluate on step intervals, not per epoch",
        "",
        "With a single epoch, per-epoch evaluation yields **one data point** - not a",
        "curve, and unable to show whether the run saturated or started degrading. That",
        "was the diagnostic that mattered most on the failed attempt. `SFTConfig` now",
        "uses `eval_strategy='steps'` with four evaluations per run at any epoch count.",
    ),
    code(
        "# Results of the final run. All three monotonic, converging, no degradation.",
        "import json",
        "for role in ('legal', 'news', 'general_qa'):",
        "    m = json.load(open(f'adapters/{role}/training_meta.json', encoding='utf-8'))",
        "    curve = [round(p['eval_loss'], 3) for p in m['eval_history']]",
        "    print(f\"{role:11s} trainable={m['trainable_params']:>11,} \"",
        "          f\"({100 * m['trainable_params'] / m['total_params']:.2f}%)  \"",
        "          f\"train_loss={m['final_train_loss']:.3f}  {m['duration_s']/60:5.1f} min  \"",
        "          f\"peak_vram={m['peak_vram_mib']} MiB\")",
        "    print(f'    eval curve: {curve}')",
    ),
    md(
        "Measured final run:",
        "",
        "| adapter | eval curve (25%->100%) | train loss | trainable | time |",
        "|---|---|---|---|---|",
        "| legal | 1.310 -> 1.203 -> 1.165 -> **1.160** | 1.409 | 24.3 M (0.75%) | 18.6 min |",
        "| news | 1.934 -> 1.909 -> 1.904 -> **1.904** | 1.949 | 29.9 M (0.96%) | 28.2 min |",
        "| general_qa | 3.959 -> 2.185 -> 1.666 -> **1.648** | 4.013 | 28.2 M (1.12%) | 44.2 min |",
        "",
        "**Note on 'identical budget':** what is held identical is the *budget*, not the",
        "resulting adapter capacity. The same rank yields different trainable counts",
        "across architectures, so the news expert gets ~23% more capacity than the legal",
        "one. That is inherent to specialising three different families and compounds the",
        "model-position entanglement in Threats to Validity.",
    ),
    md(
        "## 3.3 Loss is not a quality signal here",
        "",
        "**Do not conclude an adapter is good from its loss curve.** An earlier adapter",
        "set reduced held-out loss by 46-72% and generated degenerate word-salad in the",
        "deployed graph. Every quality judgement in nb 04 is made against the *base",
        "model* and against *real prompts*, never against training loss.",
    ),
    code(
        "# Held-out loss of the UNADAPTED base models, for reference.",
        "# Needed because the first eval point already contains a full epoch of training,",
        "# so an epoch-to-epoch curve is blind to everything learned in epoch 1. Judged",
        "# on that curve alone the news adapter looked inert - yet it had cut loss from",
        "# 2.994 to 1.630 within one epoch and then saturated.",
        "!.venv\\Scripts\\python.exe finetune\\base_eval_loss.py",
    ),
    md(
        "Measured (earlier 3-epoch adapter set, illustrating the point):",
        "",
        "| role | base | best | gain |",
        "|---|---|---|---|",
        "| legal | 2.958 | 0.816 | -72% |",
        "| news | 2.994 | 1.630 | -46% |",
        "| general_qa | 3.449 | 1.096 | -68% |",
        "",
        "Large gains - and that set still produced unusable output. Hence nb 04.",
    ),
    md(
        "## 3.4 Abandoned attempts, for the record",
        "",
        "| attempt | settings | outcome |",
        "|---|---|---|",
        "| 1 | 3 ep, lr 2e-4, 512 tok, 2500 ex | 83% of NewsQA targets truncated away; news adapter learned nothing |",
        "| 2 | 3 ep, lr 2e-4, 512 tok, 1500 ex | all three trained, but epoch 3 degraded all of them; answers collapsed in length |",
        "| **3 (final)** | **1 ep, lr 5e-5, 1024 tok, 1500 ex** | **clean monotonic convergence** |",
        "",
        "Attempt 2 was discarded and all three retrained rather than patching only the",
        "news adapter, because a mixed budget is the confound described at the top.",
    ),
)

# ===========================================================================
# 04 - Validation and debugging
# ===========================================================================
nb4 = notebook(
    md(
        "# 04 - Validation, Diagnostics, and the Bugs That Mattered",
        "",
        "This notebook is mostly about **how a working pipeline can look broken and a",
        "broken one can look working**. Every check here exists because a cheaper check",
        "gave the wrong answer.",
    ),
    md(
        "## 4.1 Validate adapters - against the base model and at real prompt length",
        "",
        "Two independent checks, because they fail differently:",
        "",
        "1. **Held-out loss vs the UNADAPTED base** - not epoch-to-epoch (blind to epoch 1).",
        "2. **Behavioural divergence** - same probes from adapted and unadapted weights.",
        "",
        "Critically, probes are rendered through the **real agent templates**",
        "(`config.LEGAL_PROMPT` etc.) with real retrieved context.",
    ),
    code(
        "!.venv\\Scripts\\python.exe finetune\\validate_adapters.py --max-new-tokens 400",
    ),
    md(
        "### The validation harness itself produced two wrong verdicts",
        "",
        "**Wrong verdict 1 - passed broken adapters.** Original probes were ~50-token bare",
        "questions. Output looked merely *terse*; the degeneration only appeared at ~1400",
        "tokens. Short probes cannot reveal long-context failure.",
        "",
        "**Wrong verdict 2 - failed working adapters.** The first fix wrapped probes in an",
        "*improvised* scaffold (`'You are a legal expert... citing specific Articles'`)",
        "rather than the real `LEGAL_PROMPT`. The adapters are **format-sensitive by",
        "construction** - they are trained on targets shaped like those templates. Under",
        "the improvised prompt the legal adapter answered in **36 words** where its base",
        "used 213, reading as a severe regression. Under the real prompt, the same",
        "adapter produced **165-687 words of correct IRAC citing the right article**,",
        "while the base model **fabricated a citation** (`Article 2(1)(b)`) or abstained.",
        "",
        "**Also: the pass criteria measure whether the adapter CHANGED the model, not",
        "whether it improved it.** Divergence and loss gain both passed an adapter that",
        "was answering with a third of its base model's words. The report now prints word",
        "ratio and citation counts next to the verdict.",
    ),
    code(
        "# Final measured validation, real agent prompts:",
        "#",
        "#   role        probe tok  divergence  words T/B    ratio   citations T/B",
        "#   legal       1674       98.3%       165 vs 7     23.5x   1.0 vs 0.0",
        "#   news         243       93.3%       214 vs 72     3.0x   0.0 vs 0.0",
        "#   general_qa   262       89.7%       120 vs 59     2.0x   0.0 vs 0.0",
        "#",
        "# The legal base model's '7 words' is the abstention sentence:",
        "#   'Insufficient authoritative support -- recommend expert review.'",
        "# So at a real prompt the UNADAPTED model declines while the adapter answers and",
        "# cites Article 43 / Article 8. That is a behavioural change in abstention, which",
        "# this paper treats as a first-class outcome - and the benchmark, not two probes,",
        "# is what settles whether it is correct.",
        "import json",
        "r = json.load(open('finetune/adapter_validation.json', encoding='utf-8'))",
        "for e in r['roles']:",
        "    print(f\"{e['role']:11s} {e['status']:7s} divergence={e['mean_diff_ratio']:.3f} \"",
        "          f\"words {e['tuned_mean_words']:.0f}/{e['base_mean_words']:.0f} \"",
        "          f\"gain_from_base={e.get('gain_from_base')}\")",
    ),
    md(
        "## 4.2 Direct expert probe - bypassing the graph",
        "",
        "`/chat` cannot answer *'is this adapter usable'*, because the answer has passed",
        "through the aggregator, validator and response nodes - any of which could be the",
        "degrading step. This calls `LegalAgent` directly with the real retrieval stack",
        "and the real prompt.",
    ),
    code("!.venv\\Scripts\\python.exe probe_legal_expert.py"),
    md(
        "Measured: at a **1292-token** production prompt the tuned legal expert produced",
        "**687 words** of correct IRAC citing **Article 6(3)** (correct for high-risk",
        "classification), while the base produced 165 words citing **Article 2(1)(b)** -",
        "a fabricated citation with a fabricated quote.",
    ),
    md(
        "## 4.3 THE decisive bug - coordination nodes were loading an expert's adapter",
        "",
        "The experts were fine all along. The word-salad came from the **aggregator and",
        "response nodes**, which are supposed to run the general expert's base weights",
        "with the adapter **disabled**.",
        "",
        "```",
        "[local_models] loading role=general_qa base=granite-3.1-2b-instruct adapter=yes   <-- WRONG",
        "aggregator model: granite-3.1-2b-instruct  adapter=.../adapters/general_qa",
        "```",
        "",
        "**Cause - one argument.** `LocalChatModel.__init__` called",
        "`get_loaded_model(self.role)`, but `self.role` was *already resolved*:",
        "`resolve_role('aggregator') -> 'general_qa'`. `get_loaded_model` derives the",
        "adapter decision from the role it is handed, so it answered for the **expert**",
        "instead of the coordination node.",
        "",
        "Every coordination node - aggregator, validator, response, router, planner,",
        "memory, QueryAnalyzer - ran with the general expert's LoRA attached.",
        "",
        "**Why it survived a fix:** `get_loaded_model` *was* corrected to consult the",
        "requested role, and a regression test asserted exactly that - by calling",
        "`get_loaded_model('aggregator')` directly. It never went through the constructor,",
        "which is the only place the defect lived.",
        "",
        "**Fix:** pass the *requested* role. `get_loaded_model(role)`, not `self.role`.",
    ),
    code(
        "# The probe that exposed it: hold the model fixed, vary only how many expert",
        "# answers are fed in, so the prompt walks from ~1500 to ~2100 tokens.",
        "!.venv\\Scripts\\python.exe probe_aggregator.py",
    ),
    md(
        "### Before and after, same probe",
        "",
        "| input | before (`adapter=yes`) | after (`adapter=no`) |",
        "|---|---|---|",
        "| 1 expert, 1546 tok | word-salad, 1024 tok, **hit_cap=True**, 159 s | **228 words**, 331 tok, hit_cap=False, **42 s** |",
        "| 2 experts, 1690 tok | word-salad, 1024 tok, hit_cap=True, 165 s | 233 words, 352 tok, hit_cap=False, 43 s |",
        "| 3 experts, 2102 tok | word-salad, 1024 tok, hit_cap=True, 165 s | 214 words, 312 tok, hit_cap=False, 37 s |",
        "",
        "Degeneration at **every** prompt size, so it was never length-related - which is",
        "why a 1024-token retrain did not help.",
        "",
        "**It was also the runtime problem.** The broken node never emitted a stop token,",
        "so it generated the full 1024-token budget every time (`hit_cap=True` on all",
        "three). ~4x faster once fixed. Every other coordination node was equally",
        "afflicted - the `response` node took 240 s in one run for the same reason.",
    ),
    md(
        "## 4.4 Missing repetition penalty (a real, separate defect)",
        "",
        "`transformers` defaults `repetition_penalty` to **1.0 - none**. Ollama, which",
        "every pre-pivot run used, applies **1.1** by default. Moving generation from",
        "Ollama to raw `transformers` silently removed repetition control the earlier",
        "experiments always had, and 2-3B models asked for 1024 tokens collapse into",
        "loops (`'Under Article Article Article...'` x80).",
        "",
        "Fixed via `config.LOCAL_REPETITION_PENALTY = 1.1`, chosen to **match Ollama's",
        "default** so decoding stays comparable with the pre-pivot runs rather than",
        "introducing a second uncontrolled difference.",
        "",
        "Also now recorded per generation: **`hit_token_cap`** - hitting the cap exactly",
        "is the signature of a model that never emitted its stop token.",
    ),
    md(
        "## 4.5 Diagnostic traps - read this before debugging anything here",
        "",
        "| trap | consequence |",
        "|---|---|",
        "| Reusing one `session_id` across probes | the memory agent loads persisted history, so each probe echoes the previous answer. A freshly retrained adapter reproduced the OLD adapter's output almost verbatim and looked unchanged. `benchmark.py` is safe - unique id per (arm, mode, query, repeat). |",
        "| Short probes | hide long-context degeneration entirely |",
        "| Improvised prompt scaffolds | adapters are format-sensitive; measures a condition they never face |",
        "| Trusting the loss curve | 46-72% loss reduction alongside unusable generation |",
        "| Epoch-to-epoch curves | blind to everything learned in epoch 1; made a working adapter look inert |",
        "| Bare `python` | system interpreter lacks peft/accelerate/bitsandbytes; models fail to load with a misleading message |",
        "| Ollama down | retrieval silently degrades to BM25-only and still completes |",
    ),
)

# ===========================================================================
# 05 - Benchmark, analysis, paper
# ===========================================================================
nb5 = notebook(
    md(
        "# 05 - Benchmark, Analysis, and Paper Outputs",
        "",
        "**Design:** 30 queries x 3 topologies x 3 repeats x 2 arms = **540 runs**.",
        "",
        "- Topologies: `all` (sequential), `parallel` (concurrent), `graph_engineering` (converging + loop engineering).",
        "- Arms: `peft` (adapters loaded) and `base` (identical models, no adapters).",
        "",
        "The `base` arm is the control that makes RQ2 answerable. Without it, a topology",
        "ranking over specialised agents cannot be distinguished from one that would have",
        "come out the same way with no specialisation at all.",
        "",
        "`single`, `legal_first`, `planner_based`, `verify_only` and",
        "`legal_news_parallel` remain implemented and selectable, but are out of scope.",
    ),
    md(
        "## 5.1 Preflight",
        "",
        "Run these before committing to a multi-hour job. Each guards a failure that",
        "otherwise produces a complete-looking but invalid dataset.",
    ),
    code(
        "# 1. Corpus present (several hundred chunks, not tens)",
        "import utils; print('chunks:', utils.get_db_document_count())",
    ),
    code(
        "# 2. Ollama up - embeddings only, but retrieval silently degrades without it",
        "import config, requests",
        "print(requests.get(config.OLLAMA_BASE_URL + '/api/tags', timeout=8).status_code)",
    ),
    code(
        "# 3. Code invariants. Must all pass - these guard the defects that",
        "#    invalidated earlier runs.",
        "!.venv\\Scripts\\python.exe -m pytest tests -q",
    ),
    code(
        "# 4. Adapters present and non-inert",
        "!.venv\\Scripts\\python.exe finetune\\validate_adapters.py",
    ),
    code(
        "# 5. Smoke test - 1 query x 3 topologies x 1 repeat PER ARM, separate output file",
        "!powershell -File run_experiment.ps1 -Smoke",
    ),
    md(
        "### Inspect the smoke answers - the most important check in the process",
        "",
        "Any of these means **stop**, not proceed:",
        "",
        "| observation | cause |",
        "|---|---|",
        "| abstention sentence in every mode | retrieval is empty |",
        "| `peft` and `base` answers identical | adapters inert, or the arm switch is not taking effect |",
        "| all topologies identical within an arm | sampling off; `LEGALAI_DETERMINISTIC` must be `0` |",
        "| canned GPAI provider-tier template | COMPL-AI enabled, bypassing the graph |",
    ),
    code(
        "import json",
        "for r in map(json.loads, open('benchmark_runs_smoke.jsonl', encoding='utf-8')):",
        "    if r.get('success'):",
        "        print(r['arm'].ljust(5), r['mode'].ljust(9), f\"{r['elapsed_s']:7.1f}s\",",
        "              '|', repr(r.get('response', ''))[:110])",
    ),
    md(
        "## 5.2 The full run",
        "",
        "`-BenchmarkOnly` stops before analysis, because the reference answers still need",
        "human review. Runs both arms in sequence (`peft` then `base`), appending into one",
        "`benchmark_runs.jsonl` distinguished by an `arm` column.",
    ),
    code(
        "!powershell -File run_experiment.ps1 -BenchmarkOnly",
        "",
        "# If it dies partway, resume without losing work:",
        "#   powershell -File run_experiment.ps1 -Resume -BenchmarkOnly",
        "# Rows are flushed after every single run, so a crash at run 400 keeps 399.",
    ),
    md(
        "### Operational notes",
        "",
        "- **Do not run anything else GPU-heavy.** With ~180 MiB spare VRAM another CUDA",
        "  process causes an out-of-memory failure, not just noisy latency.",
        "- **Mains power, sleep disabled.** Battery throttling distorts the latency the",
        "  paper reports; sustained load already took step times from 5.2 to 9.7 s during",
        "  training.",
        "- `REQUEST_TIMEOUT_S` is **3600**, not 600. The validator can send the whole graph",
        "  round again (`MAX_ITERATIONS=2`), and retries are the common case - 508 of 630",
        "  pre-pivot rows show 20+ graph steps against 14-17 for a single pass. A",
        "  10-minute ceiling would convert ordinary behaviour into recorded failures and",
        "  bias results toward whichever topology retries least.",
    ),
    code(
        "# Abstention rate per arm and topology - report this.",
        "import json, collections",
        "rows = [json.loads(l) for l in open('benchmark_runs.jsonl', encoding='utf-8') if l.strip()]",
        "c = collections.Counter((r['arm'], r['mode'], bool(r.get('abstained')))",
        "                        for r in rows if r.get('success'))",
        "for (arm, mode, ab), n in sorted(c.items()):",
        "    print(arm.ljust(5), mode.ljust(9), 'abstained' if ab else 'answered', n)",
    ),
    md(
        "## 5.3 Human steps - only Charbel can do these",
        "",
        "1. **Review the 30 reference answers** in `eval_dataset.json`. They were drafted",
        "   by a model and are all flagged `needs_review: true`. Every quality metric is",
        "   measured against them.",
        "2. **Relevance annotation** (`scripts/annotate_relevance.py`), or accept that",
        "   retrieval metrics stay suppressed. Do not re-enable them any other way: the",
        "   previous labels were copies of the retriever's own output, which made",
        "   precision@5 equal to 1.0 by construction.",
    ),
    md(
        "## 5.4 Analysis",
        "",
        "Two comparison families, Holm-corrected **within each family separately**:",
        "",
        "- **RQ1/RQ3** - all three pairs of topologies, run *within* an arm (never across,",
        "  which would confound structure with specialisation).",
        "- **RQ2** - `peft` vs `base` within each topology.",
        "",
        "Experimental unit is the **query**; repeats are averaged within each",
        "(query, topology, arm) cell first. A positive median difference and positive",
        "Cliff's delta both mean the **first-named** side scored higher.",
    ),
    code(
        "# Judge sanity + cost before spending on 540 answers",
        "!.venv\\Scripts\\python.exe llm_judge.py --check",
    ),
    code(
        "!.venv\\Scripts\\python.exe analyze_results.py",
        "",
        "# Watch for:",
        "#   'WARNING some rows have no arm field'          -> pre-pivot rows mixed in",
        "#   'NOTE no ablation results'                     -> RQ2 unanswerable, drop it",
        "#   'WARNING latency drifted N% within an arm'     -> between-arm latency",
        "#                                                     comparison uninterpretable",
        "#   'WARNING gold answers still flagged needs_review'",
    ),
    md(
        "### The latency-drift check",
        "",
        "The arms run as **consecutive passes**, not interleaved (six co-resident models",
        "will not fit, so adapters cannot be swapped per query). Anything varying slowly",
        "over a multi-day run - thermal throttling above all - therefore falls",
        "disproportionately on whichever arm ran second, and `elapsed_s` is one of the",
        "tested metrics.",
        "",
        "Every run records `started_at_utc`; the analysis reports within-arm drift between",
        "the first and last decile and warns above 15%. It **reports** rather than",
        "corrects: regressing latency on wall-clock time would hide a measurement problem",
        "behind a statistical one. Topology comparisons are unaffected - modes interleave",
        "within an arm.",
    ),
    code(
        "!.venv\\Scripts\\python.exe evaluate_workflows.py      # metrics_table.tex + ablation table",
        "!.venv\\Scripts\\python.exe make_paper_figures.py      # fig1-fig5",
        "!.venv\\Scripts\\python.exe make_topology_figure.py    # fig0",
    ),
    code(
        "!.venv\\Scripts\\python.exe scripts\\print_summary.py",
    ),
    md(
        "## 5.5 Paper outputs",
        "",
        "Upload to Overleaf: `main.tex`, `references.bib`, `metrics_table.tex`,",
        "`metrics_table_ablation.tex`, and `paper_figures/*.png` into `figures/`.",
        "",
        "`main.tex` uses `\\TBD{}` for every unfilled quantitative claim, rendered in red.",
        "**A `\\TBD{}` surviving into a submitted PDF is a bug, not a rounding decision.**",
        "They are filled from `results.json` - never typed in by hand.",
    ),
    code(
        "# Count remaining placeholders",
        "import re",
        "tex = open('../main.tex', encoding='utf-8').read()",
        "print('TBD placeholders:', tex.count('\\\\TBD{'))",
        "labels = set(re.findall(r'\\\\label\\{([^}]+)\\}', tex))",
        "refs = set(re.findall(r'\\\\ref\\{([^}]+)\\}', tex))",
        "print('dangling refs:', sorted(refs - labels) or 'none')",
    ),
    code(
        "# Snapshot the run. Provenance is a hash of the source files that produced the",
        "# numbers - this project is kept fully local with no git repository, so there is",
        "# no commit id. Arguably better: it reflects the code that actually ran.",
        "!.venv\\Scripts\\python.exe scripts\\snapshot_run.py --label peft-pivot",
    ),
)

write("01_environment_and_hardware.ipynb", nb1)
write("02_dataset_preparation.ipynb", nb2)
write("03_qlora_training.ipynb", nb3)
write("04_validation_and_debugging.ipynb", nb4)
write("05_benchmark_analysis_and_paper.ipynb", nb5)
print("\nAll notebooks written to", OUT_DIR)
